name: Build and Release Monkey

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build Binaries
        uses: sosedoff/actions/golang-build@master
        with:
          args: darwin/amd64 darwin/386 linux/amd64 linux/arm64 linux/arm linux/386 windows/amd64 windows/386
        env:
          GO111MODULE: on

      - name: Release Binaries
        uses: ncipollo/release-action@v1
        with:
          artifacts: ".release/*"
          token: ${{ secrets.GITHUB_TOKEN }}
